############################################################
#
# web访问端口号  约定：8080
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
### 配置数据源和mybatis
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckilling?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 100                 # 最小连接数
      maximum-pool-size: 1000           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
      servlet:
        multipart:
          max-file-size: 512000     # 文件上传大小限制为500kb
          max-request-size: 512000  # 请求大小限制为500kb
  redis:
    cluster:
      nodes:
        - 1.116.87.203:7001
        - 1.116.87.203:7002
        - 1.116.87.203:7003
        - 1.116.88.73:7004
        - 1.116.88.73:7005
        - 1.116.88.73:7006
      max-redirects: 3
    jedis:
      pool:
        max-idle: 2000
        max-wait: -1
        max-active: 2000
        min-idle: 200
    timeout: 5000
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      html-application-cache: true
      compressed: true
    static-locations: classpath:/static/
    cache:
      period: 3000
  rabbitmq:
    host: 1.116.87.203
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        # 消费者的数量
        max-concurrency: 10
        # 队列中出队每次出几个 多几个，加快出队速率。但是太多的话，数据会一直得不到处理
        prefetch: 1
        # 默认消费者自动启动
        auto-startup: true
        # 消费者消费失败自动把数据压回去
        default-requeue-rejected: true
        # 重置的信息
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 1.0
############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: top.candyboy.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，比如判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
#  mapper-locations: classpath:/top/candyboy/pojo/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 10
    default-statement-timeout: 3000