server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckilling
    username: root
    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:templates/
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3
    jedis:
      pool:
        max-idle: 10
        max-wait: 3
        max-active: 10
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      html-application-cache: true
      compressed: true
    static-locations: classpath:/static/
    cache:
      period: 3000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
mybatis:
  type-aliases-package: top.candyboy.pojo
#  mapper-locations: classpath:/top/candyboy/pojo/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 10
    default-statement-timeout: 3000